src/Entity/User.php
<?php
//USER ENTITY

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\OneToMany;
use phpDocumentor\Reflection\Types\Integer;
use PHPUnit\Util\Json;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    //ID
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column()]
    private ?int $id = null;

    //EMAIL (délka:180, každý email musí být unikátní)
    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    //Uživatelské role
    //1. Role = ROLE_USER
    //2. Role = ROLE_ADMIN
    #[ORM\Column(type:"json")]
    private array $roles = [];

    //Hashované heslo
    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    //JMÉNO = text o maximální délce 255 znaků
    #[ORM\Column(length: 255)]
    private ?string $Firstname = null;

    //PŘIJMENÍ = text o maximální délce 255 znaků
    #[ORM\Column(length: 255)]
    private ?string $Lastname = null;

    //UČÁSTNÍCI = jinak řečeno jiní uživatelé chatu, kteří jsou mapovaní pomocí user_id
    #[ORM\OneToMany(targetEntity: Participant::class, mappedBy: 'user_id')]
    private $participant;

    //ZPRÁVY
    #[ORM\OneToMany(targetEntity: Message::class, mappedBy: "user_id")]
    private $messages;

    public function __construct()
    {
        $this->participant = new ArrayCollection();
        $this->messages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstname(): ?string
    {
        return $this->Firstname;
    }

    public function setFirstname(string $Firstname): self
    {
        $this->Firstname = $Firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->Lastname;
    }

    public function setLastname(string $Lastname): self
    {
        $this->Lastname = $Lastname;

        return $this;
    }


    /**
     * @return Collection|Participant[]
     */
    public function getParticipants(): Collection
    {
        return $this->participant;
    }

    public function addParticipant(Participant $participant): self
    {
        if (!$this->participant->contains($participant)) {
            $this->participant[] = $participant;
            $participant->setUserId($this);
        }

        return $this;
    }

    public function removeParticipant(Participant $participant): self
    {
        if ($this->participant->contains($participant)) {
            $this->participant->removeElement($participant);
            // set the owning side to null (unless already changed)
            if ($participant->getUserId() === $this) {
                $participant->setUserId(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Message[]
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(Message $message): self
    {
        if (!$this->messages->contains($message)) {
            $this->messages[] = $message;
            $message->getUserId($this);
        }

        return $this;
    }

    public function removeMessage(Message $message): self
    {
        if ($this->messages->contains($message)) {
            $this->messages->removeElement($message);
            // set the owning side to null (unless already changed)
            if ($message->getUserId() === $this) {
                $message->setUserId(null);
            }
        }

        return $this;
    }

}

src/Controller/HomeController.php
<?php

namespace App\Controller;

//use Firebase\JWT\Key;
use Lcobucci\JWT\Signer\Key;
use Lcobucci\JWT\Signer\Hmac\Sha256;
use Lcobucci\JWT\Token\Builder;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Cookie;
use Symfony\Component\Mercure\Update;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mercure\HubInterface;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    #[Route('/', name: 'home')]
    public function index(HubInterface $hub): Response
    {
        $update = new Update(
            'https://example.com/books/1',
            json_encode(['status' => 'OutOfStock'])
        );

        $hub->publish($update);

        $response =  $this->render('home/index.html.twig', [
            'controller_name' => 'IndexController',
        ]);

        return new Response($response);


    }
}

templates/home/index.html.twig
{# Úvodní stránka #}

{% extends 'base.html.twig' %}

{% block title %}ChitChat{% endblock %}

{% block body %}

    <!--Vzhled stránky, když uživatel je přihlašený-->
    {% if app.user %}
        <!--Horní lišta-->
        <div class=" bg-sky-900 p-2">
            <b class=" text-white text-xl pl-4">
                {{ app.user.firstname }} <!--Jméno uživatele-->
                {{ app.user.lastname }} <!--Přijmení uživatele-->
            </b>
            <!--Tlačitko pro příhlašení neno odhlašení-->
            <a href="/{{ app.user ? 'logout' : 'login' }}" class=" float-right text-xl text-white font-semibold mx-10 hover:text-black duration-500">
                {{ app.user ? 'Logout' : 'Login' }}
            </a>
        </div>
        <!--React aplikace, kde se nachází samotný chat-->
        <div id="app"></div>
        <div {{ turbo_stream_listen('product-reviews') }}></div>
    {% else %}

    <!--Vzhled stránky, když uživatel není přihlášený-->
    <div class=" md:flex md:h-screen md:my-auto md:items-center md:justify-center text-center">

            <!--Logo ChitChat-->
            <img src="{{ asset('images/ChitChat-logo.png') }}" alt="ChitChat-logo" class=" h-96 md:block mx-auto md:mx-1">
                <div class="">
                    <!--Odstavec-->
                    <p class=" mt-4 text-slate-500 text-xl text-center">Simple chat app.</p>

                        <!--Tlačítko pro přihlášení-->
                        <button
                            type="button"
                            class="inline-block my-3 rounded bg-sky-900 px-6  pt-2.5 pb-2 leading-normal shadow-[0_4px_9px_-4px_#3b71ca] transition duration-150 ease-in-out hover:bg-sky-700 hover:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)] focus:bg-blue-600 focus:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)] focus:outline-none focus:ring-0 active:bg-primary-700 active:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)]">
                                <a href="/{{ app.user ? 'logout' : 'login' }}" class=" text-white font-bold p-1 text-lg">
                                    {{ app.user ? 'Logout' : 'Login' }}
                                </a>
                        </button>
                </div>

    </div>
    {% endif %}

{% endblock %}

{% block javascripts %}{{ encore_entry_script_tags('app') }}{% endblock %}